name = "yande"
type = "javascript"
zone_id = ""
account_id = "账户ID"
route = ""
workers_dev = true
compatibility_date = "2021-12-05"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
